# -*- coding: utf-8 -*-
"""evaluating_ptq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2oyMc51MJz247vzHjEeUKNWH1FQYOXZ
"""

import numpy as np
import tensorflow as tf
import time


start_time=time.time()
X_test = np.load('../../IJKES_Experiment/input_test_data/X_test.npy')
y_test = np.load('../../IJKES_Experiment/input_test_data/y_test.npy')
end_time=time.time()
print("Loading test data model time: ", end_time - start_time,"secs")

print("X:", X_test.shape)
print("y:", y_test.shape)


# Load the TFLite model
start_time=time.time()
interpreter = tf.lite.Interpreter(model_path="./files/pruned_model.tflite")
interpreter.allocate_tensors()
end_time=time.time()
print("Load the TFLite model time: ", end_time - start_time,"secs")


# Get input and output tensors
start_time=time.time()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
end_time=time.time()
print("Get input and output tensors time: ", end_time - start_time,"secs")


# Prepare the input data (assuming X_test is already loaded)
start_time=time.time()
input_shape = input_details[0]['shape']
input_data = X_test.astype(np.float32) # Ensure data type matches model input
end_time=time.time()
print("Prepare the input data time: ", end_time - start_time,"secs")



# Evaluate
start_time=time.time()

interpreter.set_tensor(input_details[0]['index'], np.array([input_data[0]]))
interpreter.invoke()
Output = interpreter.get_tensor(output_details[0]['index'])
print("Output=", Output, "Expected Output:", y_test[0]);

end_time=time.time()
print("single feature data evaluation time (TM): ", end_time - start_time,"secs\n\n")