# -*- coding: utf-8 -*-
"""evaluating_ptq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2oyMc51MJz247vzHjEeUKNWH1FQYOXZ
"""

import numpy as np
import tensorflow as tf
import time


start_time=time.time()
X_test = np.load('../../IJKES_Experiment/input_test_data/X_test.npy')
y_test = np.load('../../IJKES_Experiment/input_test_data/y_test.npy')
end_time=time.time()
print("Loading test data model time: ", end_time - start_time,"secs")

print("X:", X_test.shape)
print("y:", y_test.shape)


# Load the integer-only TFLite model
start_time=time.time()
interpreter_int = tf.lite.Interpreter(model_path="./files/teacher_quantized.tflite")
interpreter_int.allocate_tensors()
end_time=time.time()
print("Load the integer-only TFLite model time: ", end_time - start_time,"secs")


# Get input and output tensors
start_time=time.time()
input_details_int = interpreter_int.get_input_details()
output_details_int = interpreter_int.get_output_details()
end_time=time.time()
print("Get input and output tensors time: ", end_time - start_time,"secs")


# Prepare the input data (assuming X_test is already loaded)
# For integer models, input data often needs to be quantized
start_time=time.time()
input_scale, input_zero_point = input_details_int[0]['quantization']
input_data_int = X_test / input_scale + input_zero_point
input_data_int = input_data_int.astype(input_details_int[0]['dtype'])
end_time=time.time()
print("Prepare the input data time: ", end_time - start_time,"secs")


# Evaluate
start_time=time.time()

# Run inference for each input sample
interpreter_int.set_tensor(input_details_int[0]['index'], np.array([input_data_int[0]]))
interpreter_int.invoke()
Output = interpreter_int.get_tensor(output_details_int[0]['index'])
print("Output=", Output, "Expected Output:", y_test[0]);

end_time=time.time()
print("single feature data evaluation time (TM_PTQ_INT): ", end_time - start_time,"secs")

#print("\n\n","="*60,"\n\n")